<?php
declare(strict_types=1);
// Reuse canonical HTTP cutting/transfer/quality fixtures rather than inventing analytics-only source facts.
require __DIR__.'/mysql-cutting-integration.php';
if ($db===null) exit;
use Arasya\Operations\Tests\OperationsTestSupport as T;
use Arasya\Operations\Analytics\AnalyticsCapture;
$analyticsChecks=0;
$assert=static function(bool $condition,string $label) use(&$analyticsChecks):void { $analyticsChecks++; if (!$condition) throw new RuntimeException('FAIL analytics '.$label); };
$query=['period'=>'month','limit'=>'100'];
$grants=$pdo->query("SELECT p.permission_key FROM role_permissions rp JOIN roles r ON r.role_id=rp.role_id JOIN permissions p ON p.permission_id=rp.permission_id WHERE r.role_key='analytics-reader' ORDER BY p.permission_key")->fetchAll(PDO::FETCH_COLUMN);
$assert($grants===['analytics.view'],'new template contains only the read permission');
$assert((int)$pdo->query("SELECT COUNT(*) FROM role_permissions rp JOIN roles r ON r.role_id=rp.role_id JOIN permissions p ON p.permission_id=rp.permission_id WHERE p.permission_key='analytics.view' AND r.role_key<>'analytics-reader'")->fetchColumn()===0,'no broad role receives analytics');
foreach (['employees','departments','managers','sources','companies','orders','policy'] as $section) {
    $ok($get($root,'/management/analytics/'.$section,$query),'Root analytics '.$section);
    foreach ([$a,$b,$tailor,$manager,$manager2,$ceo] as $denied) $error($get($denied,'/management/analytics/'.$section,$query),403,'UNAUTHORIZED_ACTION');
}
$s=$pdo->prepare("SELECT role_id FROM roles WHERE role_key='analytics-reader'");$s->execute();$analyticsRole=(int)$s->fetchColumn();
$operationsRole=(int)$pdo->query("SELECT role_id FROM roles WHERE role_key='operations-manager'")->fetchColumn();
$ok(T::call($kernel,'PUT','/management/employees/'.$manager['employeeUuid'].'/roles',['roleIds'=>[$operationsRole,$analyticsRole]],['x-csrf-token'=>$root['csrf']],$root['cookie']),'accidental read-role assignment to narrow approver');
foreach (['employees','departments','managers','sources','companies','orders','policy'] as $section) $error($get($manager,'/management/analytics/'.$section,$query),403,'UNAUTHORIZED_ACTION');
$assert(!$ok($get($manager,'/management/me'),'approver with accidental read-role')['capabilities']['viewAnalytics'],'narrow approver remains server denied even with accidental analytics grant');
$staffOnly=$create('analytics-staff-only',[],['staff'],'analytics-reader');
$b2bOnly=$create('analytics-b2b-only',[],['b2b'],'analytics-reader');
foreach ([$staffOnly,$b2bOnly] as $denied) $error($get($denied,'/management/analytics/employees',$query),403,'UNAUTHORIZED_ACTION');
$sinem=$create('analytics-sinem',[],['dashboard'],'analytics-reader');
$me=$ok($get($sinem,'/management/me'),'Sinem capabilities');
$assert($me['capabilities']['viewAnalytics'] && !$me['capabilities']['manageAnalyticsPolicy'],'reader grants analytics but no Root policy');
$ok($get($sinem,'/management/analytics/employees',$query),'Sinem read');
$error($get($sinem,'/management/employees'),403,'UNAUTHORIZED_ACTION');
$error($get($sinem,'/management/cutting/devices'),403,'ROOT_REQUIRED');
$error($get($sinem,'/management/production-settings'),403,'ROOT_ONLY');
$ok(T::call($kernel,'PUT','/management/organization/ceo',['employeeId'=>$ceo['employeeUuid']],['x-csrf-token'=>$root['csrf'],'idempotency-key'=>'analytics-ceo-'.$suffix],$root['cookie']),'canonical CEO');
$ok($get($ceo,'/management/analytics/employees',$query),'canonical CEO reads analytics independently of broad CEO role');
$error(T::call($kernel,'PUT','/management/analytics/policy',['approvalGraceMinutes'=>30,'expectedVersion'=>1],['x-csrf-token'=>$sinem['csrf'],'idempotency-key'=>'analytics-denied-'.$suffix],$sinem['cookie']),403,'ROOT_REQUIRED');
$settings=$ok($get($root,'/management/analytics/policy'),'Root policy');
$policyInput=['approvalGraceMinutes'=>30,'expectedVersion'=>$settings['version']]; $policyKey='analytics-policy-'.$suffix;
$changed=$ok(T::call($kernel,'PUT','/management/analytics/policy',$policyInput,['x-csrf-token'=>$root['csrf'],'idempotency-key'=>$policyKey],$root['cookie']),'Root updates grace');
$assert($changed['approvalGraceMinutes']===30 && $changed['version']===$settings['version']+1,'optimistic policy version');
$retry=$ok(T::call($kernel,'PUT','/management/analytics/policy',$policyInput,['x-csrf-token'=>$root['csrf'],'idempotency-key'=>$policyKey],$root['cookie']),'policy retry');
$assert($changed===$retry,'policy replay exact');
$error(T::call($kernel,'PUT','/management/analytics/policy',$policyInput,['x-csrf-token'=>$root['csrf'],'idempotency-key'=>'analytics-stale-'.$suffix],$root['cookie']),409,'ANALYTICS_POLICY_CHANGED');
$error(T::call($kernel,'PUT','/management/analytics/policy',$policyInput,[],$root['cookie']),403,'CSRF_INVALID');
$error($get($root,'/management/analytics/employees',['from'=>'2026-02-30','to'=>'2026-03-01']),400,'INVALID_DATE_RANGE');
$error($get($root,'/management/analytics/employees',['from'=>'2024-01-01','to'=>'2026-01-01']),400,'INVALID_DATE_RANGE');
$detail=$ok($get($root,'/management/analytics/orders/'.$codesOrder['uuid'],$query),'whole order drilldown');
$assert(count($detail['comparableLines'])===20 && $detail['comparableLines'][0]['quantity']===2,'comparable canonical lines retain quantities without multiplying meters');
$employee=$ok($get($root,'/management/analytics/employees/'.$b['employeeUuid'],$query),'employee detail');
$assert($employee['employee']['completedOrders']>=2 && (float)$employee['employee']['completedMeters']>=30.4,'whole completed meters across transfer and 20 lines');
$assert($employee['employee']['completedHandling']['wallSeconds']['sampleCount']>=2,'final cutter handling samples present');
$assert(isset($employee['employee']['faultMeterRate']['numerator']) && !array_key_exists('score',$employee['employee']),'explainable denominators no score');
$transfers=$ok($get($root,'/management/analytics/managers',$query),'manager decisions');
$assert(count($transfers['items'])>=2 && count($transfers['requests'])>0,'manager decision and request breakdown');
$before=$pdo->query('SELECT COUNT(*) FROM order_activity_events')->fetchColumn();
$capture=new AnalyticsCapture($pdo); $count=$capture->rebuild(37);
$snapshot=$pdo->query('SELECT * FROM analytics_order_projection ORDER BY order_uuid')->fetchAll(PDO::FETCH_ASSOC);
$intervalSnapshot=$pdo->query('SELECT * FROM analytics_ownership_intervals ORDER BY order_uuid,start_version')->fetchAll(PDO::FETCH_ASSOC);
$capture->rebuild(19);
$assert($snapshot===$pdo->query('SELECT * FROM analytics_order_projection ORDER BY order_uuid')->fetchAll(PDO::FETCH_ASSOC),'rebuild idempotent projection');
$assert($intervalSnapshot===$pdo->query('SELECT * FROM analytics_ownership_intervals ORDER BY order_uuid,start_version')->fetchAll(PDO::FETCH_ASSOC),'rebuild idempotent raw intervals');
$assert($before===$pdo->query('SELECT COUNT(*) FROM order_activity_events')->fetchColumn(),'canonical history never altered');
$assert($count===(int)$pdo->query('SELECT COUNT(*) FROM operational_orders')->fetchColumn(),'bounded rebuild covers every order');
$raceWorker=$create('analytics-rebuild-race',['material-preparation'],['staff']); $raceOrder=$order('analytics-rebuild-race');
$process=proc_open([PHP_BINARY,__DIR__.'/fixtures/analytics-rebuild-worker.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['file','/dev/null','w']],$pipes);
if (!is_resource($process)) throw new RuntimeException('Cannot start rebuild test process');
fwrite($pipes[0],json_encode(['db'=>$db,'orderId'=>$raceOrder['uuid']],JSON_THROW_ON_ERROR)); fclose($pipes[0]);
stream_set_timeout($pipes[1],5);
if (trim((string)fgets($pipes[1]))!=='locked') throw new RuntimeException('Rebuild process did not acquire canonical lock');
$ok($post($raceWorker,'/orders/'.$raceOrder['id'].'/claim',T::cuttingClaim($pdo,$raceOrder['id'],$raceWorker['employeeUuid'],1)),'real claim serializes behind concurrent rebuild');
$output=stream_get_contents($pipes[1]); fclose($pipes[1]);
$assert(proc_close($process)===0 && trim($output)==='committed','rebuild transaction completed without modifying canonical history');
$s=$pdo->prepare('SELECT p.source_version,o.production_version,p.first_claim_at FROM analytics_order_projection p JOIN operational_orders o ON o.order_uuid=p.order_uuid WHERE p.order_uuid=?'); $s->execute([$raceOrder['uuid']]); $concurrent=$s->fetch(PDO::FETCH_ASSOC);
$assert((int)$concurrent['source_version']===(int)$concurrent['production_version'] && (int)$concurrent['source_version']===2 && $concurrent['first_claim_at']!==null,'concurrent rebuild cannot overwrite a newer production event with stale projection');
$ok(T::call($kernel,'PUT','/management/employees/'.$sinem['employeeUuid'].'/roles',['roleIds'=>[]],['x-csrf-token'=>$root['csrf']],$root['cookie']),'revoke analytics role');
$error($get($sinem,'/management/analytics/employees',$query),403,'UNAUTHORIZED_ACTION');
echo "PASS {$analyticsChecks} analytics integration assertions\n";
