CREATE TABLE IF NOT EXISTS order_sources (
    source_key VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    schema_version INT UNSIGNED NOT NULL DEFAULT 1,
    status VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (source_key),
    CONSTRAINT chk_order_sources_status CHECK (status IN ('active', 'inactive')),
    CONSTRAINT chk_order_sources_schema CHECK (schema_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operational_orders (
    order_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    global_order_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_key VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_order_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_number VARCHAR(120) NOT NULL,
    production_stage_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_commerce_status_code VARCHAR(100) NULL,
    source_commerce_status_label VARCHAR(160) NULL,
    production_notes VARCHAR(4000) NULL,
    operational_status VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    freshness_status VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_schema_version INT UNSIGNED NOT NULL DEFAULT 1,
    source_event_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_changed_at DATETIME(6) NOT NULL,
    last_source_seen_at DATETIME(6) NOT NULL,
    projected_at DATETIME(6) NOT NULL,
    accepted_at DATETIME(6) NULL,
    projection_hash BINARY(32) NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (order_uuid),
    UNIQUE KEY uq_operational_orders_global_id (global_order_id),
    UNIQUE KEY uq_operational_orders_source_id (source_key, source_order_id),
    KEY idx_operational_orders_stage (production_stage_id),
    KEY idx_operational_orders_updated (updated_at, order_uuid),
    KEY idx_operational_orders_source_changed (source_key, source_changed_at),
    KEY idx_operational_orders_freshness (freshness_status),
    CONSTRAINT fk_operational_orders_source FOREIGN KEY (source_key) REFERENCES order_sources (source_key) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_operational_orders_stage FOREIGN KEY (production_stage_id) REFERENCES production_stages (stage_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_operational_orders_op_status CHECK (operational_status IN ('in_progress', 'handed_over', 'unavailable')),
    CONSTRAINT chk_operational_orders_freshness CHECK (freshness_status IN ('fresh', 'stale', 'source_unavailable')),
    CONSTRAINT chk_operational_orders_schema CHECK (source_schema_version > 0),
    CONSTRAINT chk_operational_orders_version CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operational_order_items (
    item_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_item_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    product_code VARCHAR(120) NULL,
    variant VARCHAR(160) NULL,
    color VARCHAR(160) NULL,
    width_value DECIMAL(12,3) NULL,
    height_value DECIMAL(12,3) NULL,
    measurement_unit VARCHAR(20) NULL,
    meters DECIMAL(12,3) NULL,
    quantity INT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (item_uuid),
    UNIQUE KEY uq_operational_order_items_source (order_uuid, source_item_id),
    UNIQUE KEY uq_operational_order_items_line (order_uuid, line_number),
    CONSTRAINT fk_operational_order_items_order FOREIGN KEY (order_uuid) REFERENCES operational_orders (order_uuid) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_operational_order_items_qty CHECK (quantity > 0),
    CONSTRAINT chk_operational_order_items_line CHECK (line_number > 0),
    CONSTRAINT chk_operational_order_items_width CHECK (width_value IS NULL OR width_value >= 0),
    CONSTRAINT chk_operational_order_items_height CHECK (height_value IS NULL OR height_value >= 0),
    CONSTRAINT chk_operational_order_items_meters CHECK (meters IS NULL OR meters >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employee_order_relations (
    employee_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    relation_type VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
    started_at DATETIME(6) NOT NULL,
    last_action_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (employee_uuid, order_uuid),
    KEY idx_employee_order_relations_employee (employee_uuid, status, last_action_at),
    KEY idx_employee_order_relations_order (order_uuid, status),
    CONSTRAINT fk_employee_order_relations_employee FOREIGN KEY (employee_uuid) REFERENCES employees (employee_uuid) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_employee_order_relations_order FOREIGN KEY (order_uuid) REFERENCES operational_orders (order_uuid) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_employee_order_relations_type CHECK (relation_type IN ('claimed', 'assigned', 'updated', 'handover_in', 'handover_out', 'completed')),
    CONSTRAINT chk_employee_order_relations_status CHECK (status IN ('active', 'inactive'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_projection_receipts (
    source_key VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_event_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    global_order_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    payload_hash BINARY(32) NOT NULL,
    source_changed_at DATETIME(6) NOT NULL,
    outcome VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    received_at DATETIME(6) NOT NULL,
    PRIMARY KEY (source_key, source_event_id),
    KEY idx_order_projection_receipts_global (global_order_id),
    KEY idx_order_projection_receipts_received (received_at),
    CONSTRAINT fk_order_projection_receipts_source FOREIGN KEY (source_key) REFERENCES order_sources (source_key) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_order_projection_receipts_outcome CHECK (outcome IN ('applied', 'duplicate', 'out_of_order'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
